const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const money=n=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const DIVISION_GROUPS=[
{ar:'1. مجموعة المتطلبات العامة والتجهيزات',en:'General Requirements & Setup',items:[
{code:'00',ar:'متطلبات التعاقد والشراء',en:'Procurement and Contracting Requirements'},
{code:'01',ar:'المتطلبات العامة',en:'General Requirements'},
{code:'02',ar:'الظروف القائمة للموقع',en:'Existing Conditions'}]},
{ar:'2. الأعمال الإنشائية والمدنية',en:'Structure & Shell',items:[
{code:'03',ar:'الخرسانة',en:'Concrete'},{code:'04',ar:'المباني',en:'Masonry'},{code:'05',ar:'المعادن',en:'Metals'},{code:'06',ar:'الخشب والبلاستيك والمواد المركبة',en:'Wood, Plastics, and Composites'}]},
{ar:'3. الأعمال المعمارية والتشطيبات',en:'Architecture & Finishes',items:[
{code:'07',ar:'العزل والرطوبة',en:'Thermal and Moisture Protection'},{code:'08',ar:'الفتحات',en:'Openings'},{code:'09',ar:'التشطيبات',en:'Finishes'},{code:'10',ar:'المواد التخصصية',en:'Specialties'},{code:'11',ar:'المعدات',en:'Equipment'},{code:'12',ar:'التأثيث',en:'Furnishings'},{code:'13',ar:'الإنشاءات الخاصة',en:'Special Construction'},{code:'14',ar:'أنظمة النقل',en:'Conveying Equipment'}]},
{ar:'4. أعمال الخدمات الإلكتروميكانيكية',en:'MEP Services',items:[
{code:'21',ar:'أنظمة إطفاء الحريق',en:'Fire Suppression'},{code:'22',ar:'الأعمال الصحية والسباكة',en:'Plumbing'},{code:'23',ar:'التكييف والتهوية',en:'HVAC'},{code:'26',ar:'الأعمال الكهربائية',en:'Electrical'},{code:'27',ar:'أنظمة الاتصالات',en:'Communications'},{code:'28',ar:'الأنظمة الأمنية',en:'Electronic Safety and Security'}]},
{ar:'5. الأعمال الخارجية والبنية التحتية',en:'Site Utilities',items:[
{code:'31',ar:'الأعمال الترابية',en:'Earthwork'},{code:'32',ar:'التحسينات الخارجية',en:'Exterior Improvements'},{code:'33',ar:'المرافق والبنية التحتية',en:'Utilities'}]},
{ar:'6. أخرى',en:'Other',items:[{code:'OTHER',ar:'أخرى / سكوب خاص',en:'Other / Custom Scope'}]}
];
const DIVS=DIVISION_GROUPS.flatMap(g=>g.items.map(x=>({...x,groupEn:g.en,groupAr:g.ar})));
const divByCode=c=>DIVS.find(x=>x.code===c);
const divOrder=c=>{const i=DIVS.findIndex(x=>x.code===c);return i<0?999:i};
const breakdowns={entire:{label:'Entire Building',hint:'All items are grouped directly by Division.'},building:{label:'Building',hint:'Enter the building name or code, e.g. VPC Building.'},floor:{label:'Floor',hint:'Enter the floor, e.g. B2, B1, Ground Floor, L1.'},space:{label:'Space / Room',hint:'Enter room, zone or space name.'},custom:{label:'Custom Scope',hint:'Enter a package, area, phase or custom grouping.'}};
const DEFAULT={step:1,lang:'both',layout:'balanced',ori:'p',totalMode:'page',breakdown:'entire',project:{pen:'Tahakom Al-Qirawan',par:'مشروع تحكم القيروان',ten:'Bill of Quantities',tar:'جدول الكميات',pno:'THK-QRN',rev:'Rev.00'},parties:[{id:1,role:'Owner',en:'Tahakom',ar:'تحكم',logo:null},{id:2,role:'Consultant',en:'Q-Design',ar:'كيو ديزاين',logo:null}],items:[]};
let S=(()=>{try{const x=JSON.parse(localStorage.getItem('nusoq-boq-final-v1')||'null');return x?Object.assign(structuredClone(DEFAULT),x):structuredClone(DEFAULT)}catch(e){return structuredClone(DEFAULT)}})();
let timer,pid=Date.now(),iid=Date.now()+1000;
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('on');setTimeout(()=>x.classList.remove('on'),2200)}
function save(){localStorage.setItem('nusoq-boq-final-v1',JSON.stringify(S));$('#saved').textContent='All changes saved'}
function changed(){clearTimeout(timer);$('#saved').textContent='Saving…';timer=setTimeout(save,300)}
function go(n){S.step=n;$$('.screen').forEach(x=>x.classList.toggle('on',+x.dataset.screen===n));$$('.step').forEach(x=>x.classList.toggle('on',+x.dataset.step===n));$('#title').textContent=['','Create a new BOQ','Project, parties & breakdown','Page layout','BOQ Editor','Review BOQ'][n];if(n>=3)preview();if(n===4)editor();if(n===5)review();changed();window.scrollTo({top:0,behavior:'smooth'})}
$$('.next,.prev').forEach(b=>b.onclick=()=>go(+b.dataset.n));$$('.step').forEach(b=>b.onclick=()=>go(+b.dataset.step));
['pen','par','ten','tar','pno','rev'].forEach(id=>{const e=$('#'+id);e.value=S.project[id];e.oninput=()=>{S.project[id]=e.value;meta();preview();changed()}});
function meta(){$('#mproj').textContent=S.project.pen||S.project.par;$('#mtitle').textContent=S.project.ten||S.project.tar;$('#mrev').textContent=S.project.rev}
$$('[data-lang]').forEach(b=>{b.classList.toggle('on',b.dataset.lang===S.lang);b.onclick=()=>{S.lang=b.dataset.lang;$$('[data-lang]').forEach(x=>x.classList.toggle('on',x===b));preview();editor();changed()}});
function breakdownUI(){$$('[data-breakdown]').forEach(b=>b.classList.toggle('on',b.dataset.breakdown===S.breakdown));const c=breakdowns[S.breakdown];$('#breakHint').innerHTML='<b>'+c.label+':</b> '+c.hint;$('#scopeLabel').textContent=c.label;$('#scopeHint').textContent=c.hint;$('#scope').disabled=S.breakdown==='entire';if(S.breakdown==='entire')$('#scope').value='Entire Building'}
$$('[data-breakdown]').forEach(b=>b.onclick=()=>{S.breakdown=b.dataset.breakdown;breakdownUI();changed()});breakdownUI();
function parties(){const b=$('#parties');b.innerHTML='';S.parties.forEach(p=>{const d=document.createElement('div');d.className='party';d.innerHTML='<label class="logo"><input hidden type="file" accept="image/*">'+(p.logo?'<img src="'+p.logo+'">':'LOGO')+'</label><div><span class="role">'+esc(p.role)+'</span><strong>'+esc(p.en||'Unnamed')+'</strong><small dir="rtl">'+esc(p.ar||'')+'</small></div><button class="x" title="Remove">×</button>';$('input',d).onchange=()=>{const f=$('input',d).files[0];if(!f)return;const r=new FileReader();r.onload=e=>{p.logo=e.target.result;parties();preview();changed()};r.readAsDataURL(f)};$('.x',d).onclick=()=>{S.parties=S.parties.filter(x=>x.id!==p.id);parties();preview();changed()};b.appendChild(d)})}
parties();
$('#addParty').onclick=()=>$('#partyModal').classList.add('on');$('#closeParty').onclick=$('#pcancel').onclick=()=>$('#partyModal').classList.remove('on');$('#pconfirm').onclick=()=>{if(!$('#pEn').value.trim()&&!$('#pAr').value.trim()){toast('Enter a party name.');return}S.parties.push({id:pid++,role:$('#prole').value,en:$('#pEn').value.trim(),ar:$('#pAr').value.trim(),logo:null});$('#pEn').value=$('#pAr').value='';$('#partyModal').classList.remove('on');parties();preview();changed()};
$$('[data-layout]').forEach(b=>{b.classList.toggle('sel',b.dataset.layout===S.layout);b.onclick=()=>{S.layout=b.dataset.layout;$$('[data-layout]').forEach(x=>x.classList.toggle('sel',x===b));preview();changed()}});
function ori(o){S.ori=o;$('#por').classList.toggle('on',o==='p');$('#lan').classList.toggle('on',o==='l');$$('.paper').forEach(x=>{x.classList.toggle('p',o==='p');x.classList.toggle('l',o==='l')});preview();changed()}
$('#por').onclick=()=>ori('p');$('#lan').onclick=()=>ori('l');$('#tot').value=S.totalMode;$('#tot').onchange=()=>{S.totalMode=$('#tot').value;preview();changed()};ori(S.ori);
function logoHtml(p){return '<div class="plogo"><div class="img">'+(p.logo?'<img src="'+p.logo+'">':esc(p.en||p.role))+'</div><span>'+esc(p.role)+'</span></div>'}
function projectInfo(){return '<div class="project"><strong>'+esc(S.project.pen)+'</strong><span dir="rtl">'+esc(S.project.par)+'</span><span>'+esc(S.project.pno)+' • '+esc(S.project.rev)+'</span></div>'}
function headerHtml(){const ps=S.parties||[];if(S.layout==='logorow')return '<div class="h-logorow"><div class="logo-row">'+ps.map(logoHtml).join('')+'</div>'+projectInfo()+'</div>';if(S.layout==='minimal')return '<div class="h-minimal">'+projectInfo()+'<div class="mini-logos">'+ps.map(logoHtml).join('')+'</div></div>';if(S.layout==='project')return '<div class="h-project">'+projectInfo()+'<div class="all-logos">'+ps.map(logoHtml).join('')+'</div></div>';const mid=Math.ceil(ps.length/2);return '<div class="h-balanced"><div class="side-logos">'+ps.slice(0,mid).map(logoHtml).join('')+'</div>'+projectInfo()+'<div class="side-logos">'+ps.slice(mid).map(logoHtml).join('')+'</div></div>'}
function itemDesc(i){const en='<strong>'+esc(i.nameEn)+'</strong><br>'+esc(i.descEn),ar='<strong>'+esc(i.nameAr)+'</strong><br>'+esc(i.descAr);if(S.lang==='en')return '<div class="pitem">'+en+'</div>';if(S.lang==='ar')return '<div class="pitem" dir="rtl">'+ar+'</div>';return '<div class="pitem">'+en+'<div dir="rtl" style="margin-top:2px">'+ar+'</div></div>'}
function sortedItems(){return [...S.items].sort((a,b)=>(S.breakdown==='entire'?0:String(a.scope).localeCompare(String(b.scope)))||divOrder(a.division)-divOrder(b.division)||a.id-b.id)}
function grand(){return S.items.reduce((a,i)=>a+(+i.qty||0)*(+i.rate||0),0)}
function dataRows(cols=6){let out='',lastScope=null,lastDiv=null,n=1;sortedItems().forEach(i=>{if(S.breakdown!=='entire'&&i.scope!==lastScope){out+='<tr class="scopeRow"><td colspan="'+cols+'">'+esc(breakdowns[S.breakdown].label)+': '+esc(i.scope)+'</td></tr>';lastScope=i.scope;lastDiv=null}if(i.division!==lastDiv){const d=divByCode(i.division);const den=i.division==='OTHER'?(i.customEn||d.en):d.en,dar=i.division==='OTHER'?(i.customAr||d.ar):d.ar;out+='<tr class="secrow"><td colspan="'+cols+'">'+(i.division==='OTHER'?'Other / Custom Scope':'Division '+i.division)+' — '+esc(den)+' / '+esc(dar)+'</td></tr>';lastDiv=i.division}out+='<tr><td>'+n+++'</td><td>'+itemDesc(i)+'</td><td>'+esc(i.unit)+'</td><td>'+money(i.qty)+'</td><td>'+money(i.rate)+'</td><td>'+money(i.qty*i.rate)+'</td></tr>'});return out}
function paperHtml(){return '<div class="pi">'+headerHtml()+'<div class="pt">'+(S.lang==='ar'?esc(S.project.tar):S.lang==='en'?esc(S.project.ten):esc(S.project.ten)+'<br><span dir="rtl">'+esc(S.project.tar)+'</span>')+'</div><table class="ptable"><thead><tr><th>No.</th><th>Item / Description</th><th>Unit</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>'+dataRows(6)+'</tbody></table><div class="ptotal">'+(S.totalMode==='cum'?'Page / Cumulative Total':'Page Total')+': '+money(grand())+' SAR</div></div>'}
function preview(){['paperIn','paperIn2'].forEach(id=>{const e=$('#'+id);if(e)e.innerHTML=paperHtml()});$$('.paper').forEach(x=>{x.classList.toggle('p',S.ori==='p');x.classList.toggle('l',S.ori==='l')})}
function editor(){const b=$('#body');b.innerHTML='';let lastScope=null,lastDiv=null,n=1;sortedItems().forEach(i=>{if(S.breakdown!=='entire'&&i.scope!==lastScope){const r=document.createElement('tr');r.className='scopeRow';r.innerHTML='<td colspan="7"><span class="scopebadge">'+esc(breakdowns[S.breakdown].label)+'</span>'+esc(i.scope)+'</td>';b.appendChild(r);lastScope=i.scope;lastDiv=null}if(i.division!==lastDiv){const d=divByCode(i.division),den=i.division==='OTHER'?(i.customEn||d.en):d.en,dar=i.division==='OTHER'?(i.customAr||d.ar):d.ar;const r=document.createElement('tr');r.className='secrow';r.innerHTML='<td>§</td><td colspan="5"><span class="divbadge">'+(i.division==='OTHER'?'OTHER':'D'+i.division)+'</span>'+esc(den)+' / '+esc(dar)+'</td><td></td>';b.appendChild(r);lastDiv=i.division}const tr=document.createElement('tr');tr.innerHTML='<td>'+n+++'</td><td>'+itemDesc(i)+'</td><td>'+esc(i.unit)+'</td><td>'+money(i.qty)+'</td><td>'+money(i.rate)+'</td><td>'+money(i.qty*i.rate)+'</td><td><button class="x" data-del="'+i.id+'">×</button></td>';b.appendChild(tr)});$('#grand').textContent=money(grand())+' SAR';meta();preview();$$('[data-del]').forEach(x=>x.onclick=()=>{S.items=S.items.filter(i=>i.id!=x.dataset.del);editor();changed()})}
function buildDivisions(){const s=$('#division');s.innerHTML='<option value="">Select Division…</option>';DIVISION_GROUPS.forEach(g=>{const og=document.createElement('optgroup');og.label=g.ar+' — '+g.en;g.items.forEach(d=>{const o=document.createElement('option');o.value=d.code;o.textContent=d.code==='OTHER'?'Other / Custom Scope — أخرى / سكوب خاص':'Division '+d.code+' — '+d.en+' / '+d.ar;og.appendChild(o)});s.appendChild(og)})}
function updateDivHint(){const code=$('#division').value,d=divByCode(code);$('#customDiv').classList.toggle('show',code==='OTHER');$('#divhint').innerHTML=d?'<b>'+(code==='OTHER'?'Other / Custom Scope':'Division '+d.code+' — '+esc(d.en))+'</b><br><span dir="rtl">'+esc(d.ar)+'</span>':'Select the Division this item belongs to.'}
function resetItem(){['customEn','customAr','scope','nameEn','nameAr','descEn','descAr','qty','rate','customUnit'].forEach(id=>{const e=$('#'+id);e.value='';delete e.dataset.translated});$('#division').value='';$('#unit').value='';$('#customUnitWrap').style.display='none';$('#customDiv').classList.remove('show');$('#scope').value=S.breakdown==='entire'?'Entire Building':'';$$('.translation-note').forEach(e=>e.textContent='');breakdownUI()}
function openItem(){buildDivisions();resetItem();$('#itemModal').classList.add('on');$('.mcontent',$('#itemModal')).scrollTop=0}
function closeItem(){$('#itemModal').classList.remove('on')}
$('#addItem').onclick=openItem;$('#closeItem').onclick=$('#cancelItem').onclick=closeItem;$('#division').onchange=updateDivHint;$('#unit').onchange=()=>$('#customUnitWrap').style.display=$('#unit').value==='other'?'block':'none';
async function googleTranslate(text,sl,tl){const u='https://translate.googleapis.com/translate_a/single?client=gtx&sl='+sl+'&tl='+tl+'&dt=t&q='+encodeURIComponent(text);const r=await fetch(u);if(!r.ok)throw new Error('translate');const j=await r.json();return (j[0]||[]).map(x=>x[0]).join('')}
const fallbackPairs=[['توريد وتركيب','Supply and install'],['توريد و تركيب','Supply and install'],['التشطيبات','finishes'],['قواطع جبس بورد','gypsum board partitions'],['قواطع زجاجية','glass partitions'],['بلاط بورسلان','porcelain tiles'],['الأرضيات','flooring'],['الأسقف المستعارة','suspended ceilings'],['الدهانات','painting works'],['الأبواب','doors'],['النوافذ','windows'],['العزل المائي','waterproofing'],['الخرسانة المسلحة','reinforced concrete'],['الخرسانة','concrete'],['البلوك','blockwork'],['الأعمال الكهربائية','electrical works'],['الأعمال الصحية','plumbing works'],['التكييف والتهوية','HVAC']];
function fallbackTranslate(text,sl){let out=text;if(sl==='ar'){fallbackPairs.forEach(([a,e])=>out=out.replaceAll(a,e))}else{[...fallbackPairs].sort((a,b)=>b[1].length-a[1].length).forEach(([a,e])=>out=out.replaceAll(e,a))}return out===text?'['+(sl==='ar'?'Review translation':'مراجعة الترجمة')+'] '+text:out}
async function translateInto(kind,dir,btn){const from=dir==='ar-en'?'ar':'en',to=dir==='ar-en'?'en':'ar';const srcId=kind+(from==='ar'?'Ar':'En'),dstId=kind+(to==='ar'?'Ar':'En');const src=$('#'+srcId),dst=$('#'+dstId);if(!src.value.trim()){toast(from==='ar'?'اكتب النص العربي أولاً.':'Enter the English text first.');src.focus();return}btn.classList.add('busy');btn.textContent='…';try{let out='';try{out=await googleTranslate(src.value.trim(),from,to)}catch(e){out=fallbackTranslate(src.value.trim(),from)}dst.value=out;const note=$('#note'+kind[0].toUpperCase()+kind.slice(1)+(to==='ar'?'Ar':'En'));if(note)note.textContent='Translated instantly — review wording before export.';btn.closest('.field').querySelector('.translation-note').textContent='Translated instantly — review wording before export.';dst.dataset.translated='1'}finally{btn.classList.remove('busy');btn.textContent=dir==='ar-en'?'AR → EN':'EN → AR'}}
$$('[data-trans]').forEach(btn=>btn.onclick=()=>{const [kind,a,b]=btn.dataset.trans.split('-');translateInto(kind,a+'-'+b,btn)});
$('#confirmItem').onclick=()=>{const code=$('#division').value,d=divByCode(code);if(!d){toast('Choose a Division first.');$('#division').focus();return}if(code==='OTHER'&&!($('#customEn').value.trim()||$('#customAr').value.trim())){toast('Enter the custom scope name.');return}const nameEn=$('#nameEn').value.trim(),nameAr=$('#nameAr').value.trim(),descEn=$('#descEn').value.trim(),descAr=$('#descAr').value.trim();if(!(nameEn||nameAr)){toast('Enter item name.');return}if(!(descEn||descAr)){toast('Enter item description.');return}const q=+$('#qty').value,u=$('#unit').value==='other'?$('#customUnit').value.trim():$('#unit').value;if(!q||q<=0||!u){toast('Enter quantity and unit.');return}const scope=S.breakdown==='entire'?'Entire Building':$('#scope').value.trim();if(S.breakdown!=='entire'&&!scope){toast('Enter the '+breakdowns[S.breakdown].label+'.');return}const needsReview=[$('#nameEn'),$('#nameAr'),$('#descEn'),$('#descAr')].some(e=>e.dataset.translated==='1');S.items.push({id:iid++,division:code,customEn:$('#customEn').value.trim(),customAr:$('#customAr').value.trim(),scope,nameEn,nameAr,descEn,descAr,qty:q,unit:u,rate:+$('#rate').value||0,needsReview});closeItem();editor();changed();toast('Item added to BOQ.')};
function review(){const miss=S.items.filter(i=>(!i.nameEn&&!i.nameAr)||(!i.descEn&&!i.descAr)||!i.qty||!i.unit),tr=S.items.filter(i=>i.needsReview);$('#icount').textContent=S.items.length+' BOQ items';$('#tcount').textContent=tr.length+' translations need review';$('#mcount').textContent=miss.length+' incomplete items';$('#layoutReview').textContent=({balanced:'Balanced',logorow:'Logo row',minimal:'Minimal',project:'Project focus'}[S.layout]||'Layout')+' ready';const b=$('#reviewList');b.innerHTML='';if(!tr.length)b.innerHTML='<div class="hint">No translated items require review.</div>';tr.forEach(i=>{const e=document.createElement('div');e.className='reviewitem';e.innerHTML='<b>'+esc(i.nameEn||i.nameAr)+'</b><p>'+esc(i.descEn||i.descAr)+'</p><button class="btn sec">Approve translation</button>';$('button',e).onclick=()=>{i.needsReview=false;review();changed()};b.appendChild(e)})}
$('#save').onclick=()=>{save();toast('Draft saved locally.')};$('#reset').onclick=()=>{if(confirm('Reset this BOQ?')){localStorage.removeItem('nusoq-boq-final-v1');location.reload()}};
meta();preview();editor();go(S.step||1);