const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n||0));
const DIVISION_GROUPS=[
  {ar:'1. مجموعة المتطلبات العامة والتجهيزات',en:'General Requirements & Setup',divisions:[
    {code:'00',ar:'متطلبات التعاقد والشراء',en:'Procurement and Contracting Requirements',note:'Tendering, procurement and contracting requirements'},
    {code:'01',ar:'المتطلبات العامة',en:'General Requirements',note:'Site overheads, insurance and mobilization'},
    {code:'02',ar:'الظروف القائمة للموقع',en:'Existing Conditions',note:'Demolition, waste removal and site investigation'}]},
  {ar:'2. الأعمال الإنشائية والمدنية',en:'Structure & Shell',divisions:[
    {code:'03',ar:'الخرسانة',en:'Concrete',note:'Foundations, columns, slabs and reinforced concrete'},
    {code:'04',ar:'المباني',en:'Masonry',note:'Brick, blockwork and architectural masonry'},
    {code:'05',ar:'المعادن',en:'Metals',note:'Structural steel, canopies and metal works'},
    {code:'06',ar:'الخشب والبلاستيك والمواد المركبة',en:'Wood, Plastics, and Composites',note:'Carpentry, plastics and composite materials'}]},
  {ar:'3. الأعمال المعمارية والتشطيبات',en:'Architecture & Finishes',divisions:[
    {code:'07',ar:'العزل والرطوبة',en:'Thermal and Moisture Protection',note:'Roofing, waterproofing and façade protection'},
    {code:'08',ar:'الفتحات',en:'Openings',note:'Doors, windows and glazing'},
    {code:'09',ar:'التشطيبات',en:'Finishes',note:'Plaster, paint, flooring and ceilings'},
    {code:'10',ar:'المواد التخصصية',en:'Specialties',note:'Signage, toilet partitions and specialty items'},
    {code:'11',ar:'المعدات',en:'Equipment',note:'Fixed and project equipment'},
    {code:'12',ar:'التأثيث',en:'Furnishings',note:'Furniture, casework and furnishings'},
    {code:'13',ar:'الإنشاءات الخاصة',en:'Special Construction',note:'Special structures and systems'},
    {code:'14',ar:'أنظمة النقل',en:'Conveying Equipment',note:'Elevators, lifts and escalators'}]},
  {ar:'4. أعمال الخدمات الإلكتروميكانيكية',en:'MEP Services',divisions:[
    {code:'21',ar:'أنظمة إطفاء الحريق',en:'Fire Suppression',note:'Fire suppression systems'},
    {code:'22',ar:'الأعمال الصحية والسباكة',en:'Plumbing',note:'Water supply, drainage and plumbing fixtures'},
    {code:'23',ar:'التكييف والتهوية',en:'HVAC',note:'Heating, ventilation and air conditioning'},
    {code:'26',ar:'الأعمال الكهربائية',en:'Electrical',note:'Electrical power and lighting'},
    {code:'27',ar:'أنظمة الاتصالات',en:'Communications',note:'Data, telephone and communication networks'},
    {code:'28',ar:'الأنظمة الأمنية',en:'Electronic Safety and Security',note:'CCTV, access control and electronic security'}]},
  {ar:'5. الأعمال الخارجية والبنية التحتية',en:'Site Utilities',divisions:[
    {code:'31',ar:'الأعمال الترابية',en:'Earthwork',note:'Excavation, backfilling and grading'},
    {code:'32',ar:'التحسينات الخارجية',en:'Exterior Improvements',note:'Paving, landscaping and fencing'},
    {code:'33',ar:'المرافق والبنية التحتية',en:'Utilities',note:'External drainage, water and utility networks'}]}
];
const DIVISIONS=DIVISION_GROUPS.flatMap(g=>g.divisions);
const divisionByCode=code=>DIVISIONS.find(d=>d.code===String(code).padStart(2,'0'));
const divisionOrder=code=>{const i=DIVISIONS.findIndex(d=>d.code===code);return i<0?999:i};
const defaultState={
  step:1,source:'scratch',lang:'both',layout:'balanced',orientation:'portrait',bilingual:'stacked',totalMode:'page',activeSectionId:'s1',
  project:{projectEn:'Tahakom Al-Qirawan',projectAr:'مشروع تحكم القيروان',titleEn:'Bill of Quantities',titleAr:'جدول الكميات',projectNo:'THK-QRN',revision:'Rev.00'},
  parties:[{id:1,role:'Owner',en:'Tahakom',ar:'تحكم',logo:null},{id:2,role:'Consultant',en:'Q-Design',ar:'كيو ديزاين',logo:null},{id:3,role:'Main Contractor',en:'RAM',ar:'رام',logo:null}],
  sections:[{id:'s1',divisionCode:'09',en:'Finishes',ar:'التشطيبات',items:[
    {id:'i1',en:'Supply and install gypsum board partition complete with framing and accessories.',ar:'توريد وتركيب قواطع جبس بورد كاملة مع الهيكل والإكسسوارات.',unit:'m²',qty:550,rate:185,translation:'approved'},
    {id:'i2',en:'',ar:'توريد وتركيب قواطع زجاجية مكتبية شاملة جميع الإكسسوارات.',unit:'m²',qty:125,rate:680,translation:'none'},
    {id:'i3',en:'Supply and install porcelain floor tiles including adhesive and grout.',ar:'توريد وتركيب بلاط بورسلان للأرضيات شاملاً اللاصق والترويبة.',unit:'m²',qty:820,rate:145,translation:'approved'}
  ]}]
};
const state=structuredClone(defaultState);
let partySeq=4,itemSeq=4,sectionSeq=2,saveTimer;
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function load(){try{const saved=JSON.parse(localStorage.getItem('nusoq-boq-demo'));if(saved){Object.assign(state,saved);state.project={...defaultState.project,...(saved.project||{})};if(!Array.isArray(state.sections))state.sections=[];if(!Array.isArray(state.parties))state.parties=[]}}catch(e){}reseedIds();renderAll()}
function reseedIds(){partySeq=Math.max(4,...state.parties.map(p=>Number(p.id)||0))+1;itemSeq=Math.max(4,...state.sections.flatMap(s=>s.items||[]).map(i=>Number(String(i.id).replace(/\D/g,''))||0))+1;sectionSeq=Math.max(2,...state.sections.map(s=>Number(String(s.id).replace(/\D/g,''))||0))+1}
function markChanged(){$('#saveState').textContent='Saving changes…';clearTimeout(saveTimer);saveTimer=setTimeout(save,400)}
function save(){localStorage.setItem('nusoq-boq-demo',JSON.stringify(state));$('#saveState').textContent='All changes saved';$('#saveTime').textContent='Saved '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
function goStep(n){state.step=n;$$('.screen').forEach(x=>x.classList.toggle('active',+x.dataset.screen===n));$$('.step').forEach(x=>x.classList.toggle('active',+x.dataset.step===n));const titles=['','Create a new BOQ','Project & parties','Page layout','BOQ Editor','Review BOQ'];$('#screenTitle').textContent=titles[n];if(n>=3)renderPreview();if(n===4){renderEditor();renderDivisionLibrary()}if(n===5)renderReview();window.scrollTo({top:0,behavior:'smooth'});markChanged()}
$$('.next').forEach(b=>b.onclick=()=>goStep(+b.dataset.next));$$('.prev').forEach(b=>b.onclick=()=>goStep(+b.dataset.prev));$$('.step').forEach(b=>b.onclick=()=>goStep(+b.dataset.step));
$$('[data-lang]').forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;$$('[data-lang]').forEach(x=>x.classList.toggle('active',x===b));renderEditor();renderPreview();markChanged()});
$$('[data-import]').forEach(inp=>inp.onchange=()=>{if(!inp.files[0])return;state.source=inp.dataset.import;$$('.source-card').forEach(c=>c.classList.remove('selected'));inp.closest('.source-card').classList.add('selected');toast(`${inp.files[0].name} selected — import mapping will be connected in the next phase.`);markChanged()});
$('.source-card[data-source="scratch"]').onclick=()=>{state.source='scratch';$$('.source-card').forEach(c=>c.classList.remove('selected'));$('.source-card[data-source="scratch"]').classList.add('selected');markChanged()};
const fieldMap={projectEn:'projectEn',projectAr:'projectAr',titleEn:'titleEn',titleAr:'titleAr',projectNo:'projectNo',revision:'revision'};
Object.keys(fieldMap).forEach(id=>$('#'+id).addEventListener('input',e=>{state.project[fieldMap[id]]=e.target.value;renderPreview();updateEditorMeta();markChanged()}));
function syncFields(){Object.entries(fieldMap).forEach(([id,key])=>{$('#'+id).value=state.project[key]||''})}function projectData(){return state.project}
function renderParties(){const box=$('#partyList');box.innerHTML='';state.parties.forEach((p,index)=>{const el=document.createElement('div');el.className='party';el.innerHTML=`<label class="logo-uploader"><input type="file" accept="image/*" hidden>${p.logo?`<img src="${p.logo}">`:'LOGO'}</label><div><span class="role">${esc(p.role)}</span><strong>${esc(p.en||'Unnamed party')}</strong><small dir="rtl">${esc(p.ar||'')}</small><div class="party-index">Header logo ${index+1}</div></div><div class="party-actions"><button title="Delete">×</button></div>`;const fi=$('input',el);fi.onchange=()=>{const f=fi.files[0];if(!f)return;const r=new FileReader();r.onload=e=>{p.logo=e.target.result;renderParties();renderPreview();markChanged()};r.readAsDataURL(f)};$('.party-actions button',el).onclick=()=>{state.parties=state.parties.filter(x=>x.id!==p.id);renderParties();renderPreview();markChanged()};box.appendChild(el)})}
$('#addParty').onclick=()=>$('#partyModal').classList.add('show');$('#cancelParty').onclick=()=>$('#partyModal').classList.remove('show');$('#confirmParty').onclick=()=>{const en=$('#newPartyEn').value.trim(),ar=$('#newPartyAr').value.trim();if(!en&&!ar){toast('Enter at least one party name.');return}state.parties.push({id:partySeq++,role:$('#newPartyRole').value,en,ar,logo:null});$('#newPartyEn').value='';$('#newPartyAr').value='';$('#partyModal').classList.remove('show');renderParties();renderPreview();markChanged()};
$$('[data-layout]').forEach(b=>b.onclick=()=>{state.layout=b.dataset.layout;$$('[data-layout]').forEach(x=>x.classList.toggle('selected',x===b));renderPreview();markChanged()});
$('#portraitBtn').onclick=()=>setOrientation('portrait');$('#landscapeBtn').onclick=()=>setOrientation('landscape');
function setOrientation(o){state.orientation=o;$('#portraitBtn').classList.toggle('active',o==='portrait');$('#landscapeBtn').classList.toggle('active',o==='landscape');$$('.paper').forEach(p=>{p.classList.toggle('portrait',o==='portrait');p.classList.toggle('landscape',o==='landscape')});renderPreview();markChanged()}
$('#bilingualMode').onchange=e=>{state.bilingual=e.target.value;renderPreview();renderEditor();markChanged()};$('#totalMode').onchange=e=>{state.totalMode=e.target.value;renderPreview();markChanged()};
function sectionTotal(s){return (s.items||[]).reduce((a,i)=>a+(Number(i.qty)||0)*(Number(i.rate)||0),0)}function total(){return state.sections.reduce((a,s)=>a+sectionTotal(s),0)}
function descHtml(i){if(state.lang==='en')return esc(i.en||'');if(state.lang==='ar')return `<span dir="rtl">${esc(i.ar||'')}</span>`;return `${esc(i.en||'')}<br><span dir="rtl">${esc(i.ar||'')}</span>`}
function sectionTitle(s){const code=s.divisionCode?`Division ${s.divisionCode} — `:'';if(state.lang==='ar')return `${s.divisionCode?`Division ${s.divisionCode} — `:''}${esc(s.ar||s.en)}`;if(state.lang==='en')return `${code}${esc(s.en||s.ar)}`;return `${code}${esc(s.en||'')} / ${esc(s.ar||'')}`}
function logoBox(p){if(!p)return '<div class="paper-logo">LOGO</div>';return `<div class="paper-logo">${p.logo?`<img src="${p.logo}">`:esc(p.en||p.role)}</div>`}
function partyStrip(){if(!state.parties.length)return '';return `<div class="paper-party-strip">${state.parties.map(p=>`<div class="paper-party">${logoBox(p)}<span>${esc(p.role)}</span></div>`).join('')}</div>`}
function paperMarkup(){const d=projectData(),primary=state.parties[0];let header='';if(state.layout==='logos'){header=`<div class="paper-header logo-row">${partyStrip()}<div class="paper-project"><strong>${esc(d.projectEn)}</strong><span dir="rtl">${esc(d.projectAr)}</span><span>${esc(d.projectNo)} • ${esc(d.revision)}</span></div></div>`}else if(state.layout==='minimal'){header=`<div class="paper-header minimal"><div class="paper-project" style="text-align:left"><strong>${esc(d.projectEn)}</strong><span dir="rtl">${esc(d.projectAr)}</span><span>${esc(d.projectNo)} • ${esc(d.revision)}</span></div></div>${partyStrip()}`}else if(state.layout==='project'){header=`<div class="paper-header project-focus">${logoBox(primary)}<div class="paper-project"><strong>${esc(d.projectEn)}</strong><span dir="rtl">${esc(d.projectAr)}</span><span>${esc(d.projectNo)} • ${esc(d.revision)}</span></div></div>${partyStrip()}`}else{header=`<div class="paper-header minimal"><div class="paper-project"><strong>${esc(d.projectEn)}</strong><span dir="rtl">${esc(d.projectAr)}</span><span>${esc(d.projectNo)} • ${esc(d.revision)}</span></div></div>${partyStrip()}`}
let rows='',num=1;state.sections.forEach(s=>{rows+=`<tr class="paper-section"><td colspan="6">${sectionTitle(s)}</td></tr>`;(s.items||[]).forEach(i=>{rows+=`<tr><td>${num++}</td><td>${descHtml(i)}</td><td>${esc(i.unit)}</td><td>${money(i.qty)}</td><td>${money(i.rate)}</td><td>${money((i.qty||0)*(i.rate||0))}</td></tr>`})});return `<div class="paper-inner">${header}<div class="paper-title">${state.lang==='ar'?esc(d.titleAr):state.lang==='en'?esc(d.titleEn):`${esc(d.titleEn)}<br><span dir="rtl">${esc(d.titleAr)}</span>`}</div><table class="paper-table"><thead><tr><th>No.</th><th>Description</th><th>Unit</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${rows}</tbody></table><div class="paper-total"><span>${state.totalMode==='cumulative'?'Page / Cumulative Total':'Page Total'}</span><strong>${money(total())} SAR</strong></div><div class="paper-footer">NUSOQ • ${esc(d.revision)} • A4 ${state.orientation}</div></div>`}
function renderPreview(){['paperContent','editorPaperContent','reviewPaperContent'].forEach(id=>{const el=$('#'+id);if(el)el.innerHTML=paperMarkup()});$$('.paper').forEach(p=>{p.classList.toggle('portrait',state.orientation==='portrait');p.classList.toggle('landscape',state.orientation==='landscape')})}
function updateEditorMeta(){const d=projectData();$('#editorProject').textContent=d.projectEn||d.projectAr;$('#editorTitle').textContent=d.titleEn||d.titleAr;$('#editorRevision').textContent=d.revision}
function renderHead(){const h=$('#boqHead');if(state.lang==='both'&&state.bilingual==='columns')h.innerHTML='<tr><th>#</th><th>Description EN</th><th>الوصف AR</th><th>Unit</th><th>Qty</th><th>Rate</th><th>Amount</th><th>Translation</th><th></th></tr>';else h.innerHTML='<tr><th>#</th><th>Description</th><th>Unit</th><th>Qty</th><th>Rate</th><th>Amount</th><th>Translation</th><th></th></tr>'}
function renderEditor(){renderHead();const body=$('#boqBody');body.innerHTML='';let n=1;state.sections.forEach(s=>{const sr=document.createElement('tr');sr.className='section-row';const span=(state.lang==='both'&&state.bilingual==='columns')?5:4;const field=state.lang==='ar'?'ar':'en';const divBadge=s.divisionCode?`<span class="division-mini-code">D${esc(s.divisionCode)}</span>`:'';sr.innerHTML=`<td class="row-num">§</td><td colspan="${span}"><div class="division-section-label">${divBadge}<input value="${esc(s[field]||'')}" data-section="${s.id}" data-field="${field}"></div></td><td colspan="2" class="section-total"><div class="section-inline-actions"><span>Subtotal: ${money(sectionTotal(s))} SAR</span><button class="mini-btn" data-add-item-section="${s.id}">＋ Item</button></div></td><td class="row-action"><button data-del-section="${s.id}" title="Delete section">×</button></td>`;body.appendChild(sr);(s.items||[]).forEach(i=>{const tr=document.createElement('tr');const trans=i.translation==='review'?'<span class="trans-status review">Review</span>':i.translation==='approved'?'<span class="trans-status approved">Approved</span>':'<span class="trans-status">—</span>';if(state.lang==='both'&&state.bilingual==='columns'){tr.innerHTML=`<td class="row-num">${n++}</td><td><textarea data-item="${i.id}" data-field="en">${esc(i.en)}</textarea></td><td><textarea dir="rtl" data-item="${i.id}" data-field="ar">${esc(i.ar)}</textarea></td><td><input data-item="${i.id}" data-field="unit" value="${esc(i.unit)}"></td><td><input type="number" data-item="${i.id}" data-field="qty" value="${i.qty}"></td><td><input type="number" data-item="${i.id}" data-field="rate" value="${i.rate}"></td><td>${money((i.qty||0)*(i.rate||0))}</td><td>${trans}</td><td class="row-action"><button data-del-item="${i.id}">×</button></td>`}else{const fld=state.lang==='ar'?'ar':'en';tr.innerHTML=`<td class="row-num">${n++}</td><td><textarea ${fld==='ar'?'dir="rtl"':''} data-item="${i.id}" data-field="${fld}">${esc(i[fld])}</textarea></td><td><input data-item="${i.id}" data-field="unit" value="${esc(i.unit)}"></td><td><input type="number" data-item="${i.id}" data-field="qty" value="${i.qty}"></td><td><input type="number" data-item="${i.id}" data-field="rate" value="${i.rate}"></td><td>${money((i.qty||0)*(i.rate||0))}</td><td>${trans}</td><td class="row-action"><button data-del-item="${i.id}">×</button></td>`}body.appendChild(tr)})});$('#grandTotal').textContent=money(total())+' SAR';updateEditorMeta();renderPreview();bindEditor();renderDivisionCount()}
function findItem(id){for(const s of state.sections){const i=(s.items||[]).find(x=>x.id===id);if(i)return i}}
function addItemToSection(sectionId){const s=state.sections.find(x=>x.id===sectionId);if(!s)return;state.activeSectionId=s.id;s.items=s.items||[];s.items.push({id:'i'+itemSeq++,en:'',ar:'',unit:'',qty:0,rate:0,translation:'none'});renderEditor();markChanged()}
function bindEditor(){$$('[data-item]').forEach(el=>el.onchange=()=>{const i=findItem(el.dataset.item);if(!i)return;i[el.dataset.field]=['qty','rate'].includes(el.dataset.field)?Number(el.value):el.value;if(['en','ar'].includes(el.dataset.field)&&i.translation==='approved')i.translation='none';renderEditor();markChanged()});$$('[data-section]').forEach(el=>el.onchange=()=>{const s=state.sections.find(x=>x.id===el.dataset.section);if(!s)return;s[el.dataset.field]=el.value;renderPreview();renderDivisionLibrary();markChanged()});$$('[data-add-item-section]').forEach(b=>b.onclick=()=>addItemToSection(b.dataset.addItemSection));$$('[data-del-item]').forEach(b=>b.onclick=()=>{state.sections.forEach(s=>s.items=(s.items||[]).filter(i=>i.id!==b.dataset.delItem));renderEditor();markChanged()});$$('[data-del-section]').forEach(b=>b.onclick=()=>{state.sections=state.sections.filter(s=>s.id!==b.dataset.delSection);renderEditor();renderDivisionLibrary();markChanged()})}
$('#addSection').onclick=()=>{const id='s'+sectionSeq++;state.sections.push({id,divisionCode:null,en:'New Section',ar:'قسم جديد',items:[]});state.activeSectionId=id;renderEditor();renderDivisionLibrary();markChanged()};
$('#addItem').onclick=()=>{if(!state.sections.length){switchEditorTab('divisions');toast('Choose a Division first, or add a Custom Section.');return}let s=state.sections.find(x=>x.id===state.activeSectionId)||state.sections.at(-1);addItemToSection(s.id)};
function sortSections(){state.sections.sort((a,b)=>{const ao=a.divisionCode?divisionOrder(a.divisionCode):999;const bo=b.divisionCode?divisionOrder(b.divisionCode):999;return ao-bo})}
function addDivision(code,{switchBack=true,quiet=false}={}){const d=divisionByCode(code);if(!d)return;const existing=state.sections.find(s=>s.divisionCode===d.code);if(existing){state.activeSectionId=existing.id;if(!quiet)toast(`Division ${d.code} is already in this BOQ.`);if(switchBack)switchEditorTab('boq');return}const id='s'+sectionSeq++;state.sections.push({id,divisionCode:d.code,en:d.en,ar:d.ar,items:[]});state.activeSectionId=id;sortSections();renderEditor();renderDivisionLibrary();markChanged();if(!quiet)toast(`Division ${d.code} added to BOQ.`);if(switchBack)switchEditorTab('boq')}
function renderDivisionCount(){const count=state.sections.filter(s=>s.divisionCode).length;if($('#divisionCount'))$('#divisionCount').textContent=count}
function renderDivisionLibrary(){const box=$('#divisionLibrary');if(!box)return;box.innerHTML='';DIVISION_GROUPS.forEach(g=>{const wrap=document.createElement('section');wrap.className='division-group';wrap.innerHTML=`<div class="division-group-head"><strong dir="rtl">${esc(g.ar)}</strong><span>${esc(g.en)}</span></div><div class="division-list"></div>`;const list=$('.division-list',wrap);g.divisions.forEach(d=>{const added=state.sections.some(s=>s.divisionCode===d.code);const card=document.createElement('div');card.className='division-card'+(added?' added':'');card.innerHTML=`<div class="division-code">${d.code}</div><div><strong>Division ${d.code}: ${esc(d.en)}</strong><small dir="rtl">${esc(d.ar)}</small><small>${esc(d.note)}</small></div><button class="btn secondary" data-add-division="${d.code}">${added?'Added ✓':'Add to BOQ'}</button>`;$('[data-add-division]',card).onclick=()=>addDivision(d.code);list.appendChild(card)});box.appendChild(wrap)});renderDivisionCount()}
function switchEditorTab(tab){$$('[data-editor-tab]').forEach(b=>b.classList.toggle('active',b.dataset.editorTab===tab));$('#boqTab').classList.toggle('active',tab==='boq');$('#divisionsTab').classList.toggle('active',tab==='divisions');if(tab==='divisions')renderDivisionLibrary()}
$$('[data-editor-tab]').forEach(b=>b.onclick=()=>switchEditorTab(b.dataset.editorTab));
$('#addAllDivisions').onclick=()=>{let added=0;DIVISIONS.forEach(d=>{if(!state.sections.some(s=>s.divisionCode===d.code)){addDivision(d.code,{switchBack:false,quiet:true});added++}});sortSections();renderEditor();renderDivisionLibrary();markChanged();toast(added?`${added} divisions added in CSI order.`:'All listed divisions are already added.')};
const dictionary=[['قواطع زجاجية','glass partitions'],['توريد وتركيب','Supply and install'],['شاملة جميع الإكسسوارات','including all accessories'],['أرضيات','flooring'],['بلاط','tiles'],['دهان','paint'],['أبواب','doors']];
function autoTranslate(i){if(!i.en&&i.ar){let t=i.ar;dictionary.forEach(([a,e])=>t=t.replace(a,e));if(t===i.ar)t='AI translation: '+i.ar;i.en=t;i.translation='review'}else if(!i.ar&&i.en){i.ar='ترجمة آلية: '+i.en;i.translation='review'}}
$('#translateAll').onclick=()=>{state.sections.forEach(s=>(s.items||[]).forEach(autoTranslate));renderEditor();toast('Missing descriptions translated. Review is required before export.');markChanged()};$('#togglePreview').onclick=()=>$('#editorLayout').classList.toggle('preview-hidden');
function reviewStats(){const items=state.sections.flatMap(s=>s.items||[]),translations=items.filter(i=>i.translation==='review'),missing=items.filter(i=>!(i.en||i.ar)||!i.unit||!Number(i.qty));return {items,translations,missing}}
function renderReview(){const r=reviewStats();$('#itemCheck').textContent=`${r.items.length} BOQ items`;$('#translationCheck').textContent=`${r.translations.length} translations need review`;$('#missingCheck').textContent=`${r.missing.length} incomplete items`;$('#translationCard').style.opacity=r.translations.length?1:.55;$('#missingCard').style.opacity=r.missing.length?1:.55;const list=$('#translationList');list.innerHTML='';if(!r.translations.length)list.innerHTML='<div class="hint">All generated translations are approved.</div>';r.translations.forEach(i=>{const el=document.createElement('div');el.className='review-item';el.innerHTML=`<div class="top"><strong>Translation review</strong><span class="review-chip">Review required</span></div><p dir="rtl">${esc(i.ar)}</p><textarea>${esc(i.en)}</textarea><button class="btn secondary">Approve translation</button>`;const ta=$('textarea',el);$('button',el).onclick=()=>{i.en=ta.value;i.translation='approved';renderReview();renderEditor();markChanged()};list.appendChild(el)});const ready=!r.translations.length&&!r.missing.length;$('#exportStatus').textContent=ready?'Ready to export':'Review required';$('#exportHint').textContent=ready?'All checks passed. Prototype export buttons are ready.':'Resolve the highlighted items before final export.';$('#pdfExport').disabled=!ready;$('#excelExport').disabled=!ready;renderPreview()}
$('#approveAll').onclick=()=>{state.sections.flatMap(s=>s.items||[]).forEach(i=>{if(i.translation==='review')i.translation='approved'});renderReview();renderEditor();markChanged();toast('All translations approved.')};$('#pdfExport').onclick=()=>toast('PDF export will be connected after the BOQ workflow is approved.');$('#excelExport').onclick=()=>toast('Excel export will be connected after the BOQ workflow is approved.');
$('#saveBtn').onclick=()=>{save();toast('Draft saved locally.')};$('#resetBtn').onclick=()=>{if(confirm('Reset the BOQ prototype to its sample data?')){localStorage.removeItem('nusoq-boq-demo');location.reload()}};
function renderAll(){syncFields();$$('[data-lang]').forEach(x=>x.classList.toggle('active',x.dataset.lang===state.lang));$$('.source-card').forEach(c=>c.classList.remove('selected'));const src=state.source==='scratch'?$('.source-card[data-source="scratch"]'):$(`[data-import="${state.source}"]`)?.closest('.source-card');if(src)src.classList.add('selected');$$('[data-layout]').forEach(x=>x.classList.toggle('selected',x.dataset.layout===state.layout));$('#bilingualMode').value=state.bilingual;$('#totalMode').value=state.totalMode;renderParties();setOrientation(state.orientation);renderEditor();renderDivisionLibrary();switchEditorTab('boq');goStep(state.step||1)}
load();