(()=>{
'use strict';
const KEY='nusoq-mvp-account-v2';
const TEAM_KEY='nusoq-mvp-team-v2';
const MODE_KEY='nusoq-workspace-mode';
const INCLUDED_BUSINESS_SEATS=6;
const TOOLS={
  boq:{name:'BOQ Creator',href:'boq-hub.html'},
  specs:{name:'Specifications',href:'specs.html'},
  cost:{name:'Cost Control',href:'cost-control.html'},
  tasks:{name:'My Tasks',href:'tasks.html'},
  reports:{name:'Daily Report',href:'plans.html?tool=reports'},
  dashboard:{name:'Smart Dashboard',href:'plans.html?tool=dashboard'},
  formatter:{name:'BOQ Formatting',href:'plans.html?tool=formatter'},
  cad:{name:'CAD Takeoff',href:'#'}
};
const defaults={
  mode:'personal',
  user:{name:'Basim Alzahrani',email:'eng0basim@gmail.com',initials:'BA'},
  personal:{active:true,license:'NSQ-P-DEMO-001',expiresAt:'2026-10-31',tools:['boq','specs','cost','tasks']},
  business:{active:true,license:'NSQ-B-DEMO-001',expiresAt:'2026-10-31',company:'Nusoq Demo Engineering',includedSeats:INCLUDED_BUSINESS_SEATS,role:'Owner',tools:['boq','specs','cost','tasks']},
  sallaUrl:'',
  purchaseUrls:{},
  lastUpdated:new Date().toISOString()
};
const defaultTeam=[
  {id:'u1',name:'Basim Alzahrani',email:'eng0basim@gmail.com',role:'Owner',status:'active',tools:['boq','specs','cost','tasks'],seatType:'included'},
  {id:'u2',name:'Architect User',email:'architect@example.com',role:'Member',status:'active',tools:['boq','specs','tasks'],seatType:'included'},
  {id:'u3',name:'Mechanical User',email:'mechanical@example.com',role:'Member',status:'active',tools:['boq','specs','cost','tasks'],seatType:'included'},
  {id:'u4',name:'Structural User',email:'structural@example.com',role:'Member',status:'active',tools:['boq','specs','tasks'],seatType:'included'}
];
const clone=o=>JSON.parse(JSON.stringify(o));
function load(){
  try{
    const x=JSON.parse(localStorage.getItem(KEY)||'null')||{};
    return {...clone(defaults),...x,user:{...defaults.user,...(x.user||{})},personal:{...defaults.personal,...(x.personal||{})},business:{...defaults.business,...(x.business||{})},purchaseUrls:{...defaults.purchaseUrls,...(x.purchaseUrls||{})}};
  }catch(e){return clone(defaults)}
}
function save(a){a.lastUpdated=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(a));localStorage.setItem(MODE_KEY,a.mode)}
function account(){const a=load();const q=new URLSearchParams(location.search).get('mode');if(q==='personal'||q==='business'){a.mode=q;save(a);return a}const m=localStorage.getItem(MODE_KEY);if(m==='personal'||m==='business')a.mode=m;return a}
function mode(){return account().mode}
function setMode(m,redirect=false){if(!['personal','business'].includes(m))return;const a=account();a.mode=m;save(a);document.dispatchEvent(new CustomEvent('nusoq:mode',{detail:m}));syncShell();if(redirect)location.href='workspace.html?mode='+m}
function workspace(){const a=account();return a[a.mode]}
function hasTool(tool){const w=workspace();return !!(w&&w.active&&(w.tools||[]).includes(tool))}
function status(tool){if(tool==='cad')return 'soon';return hasTool(tool)?'active':'plan'}
function normalizeTeam(t){return (t||[]).map((m,i)=>({...m,seatType:i<INCLUDED_BUSINESS_SEATS?'included':'extra'}))}
function team(){try{return normalizeTeam(JSON.parse(localStorage.getItem(TEAM_KEY)||'null')||clone(defaultTeam))}catch(e){return normalizeTeam(clone(defaultTeam))}}
function saveTeam(t){localStorage.setItem(TEAM_KEY,JSON.stringify(normalizeTeam(t)));document.dispatchEvent(new CustomEvent('nusoq:team'))}
function seatInfo(){const t=team(),used=t.length,included=Math.min(used,INCLUDED_BUSINESS_SEATS),extra=Math.max(0,used-INCLUDED_BUSINESS_SEATS);return{used,included,extra,capacity:INCLUDED_BUSINESS_SEATS,nextIsExtra:used>=INCLUDED_BUSINESS_SEATS}}
function initials(n){return String(n||'U').split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'U'}
function formatDate(v){if(!v)return 'No expiry date';const d=new Date(v+'T12:00:00');return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}
function expiryInfo(){const w=workspace(),raw=w&&w.expiresAt;if(!raw)return{raw:'',label:'No expiry date',days:null,expired:false};const end=new Date(raw+'T23:59:59'),now=new Date(),ms=end-now,days=Math.max(0,Math.ceil(ms/86400000));return{raw,label:formatDate(raw),days,expired:ms<0}}
function expiryText(){const x=expiryInfo(),name=mode()==='business'?'Business':'Personal';if(!x.raw)return `${name} access • No expiry date`;if(x.expired)return `${name} access expired on ${x.label}`;return `${name} access • Expires ${x.label}${x.days!==null?` • ${x.days} days remaining`:''}`}
function shellHtml(){const a=account(),w=workspace(),business=a.mode==='business';return `<header class="global-head"><div class="head-left"><a class="brand" href="index.html" title="Switch workspace"><span class="brand-mark">N</span><span>NUSOQ</span></a><a class="home-link" href="workspace.html">⌂ Home</a><span class="workspace-chip ${business?'business':'personal'}">${business?'Business Workspace':'Personal Workspace'}</span></div><div class="head-right"><div class="user-wrap"><button class="user-btn" id="nusoqUserBtn"><span class="avatar">${a.user.initials||initials(a.user.name)}</span><span class="user-meta"><strong>${business?(w.company||'Business Workspace'):a.user.name}</strong><span>${business?(w.role||'Member')+' • '+(w.active?'Active':'Inactive'):'Personal • '+(w.active?'Active':'Inactive')}</span></span><span class="chev">⌄</span></button><div class="user-menu" id="nusoqUserMenu"><div class="menu-label">Workspace</div><a href="index.html">Switch Personal / Business</a><a href="account.html">Account & subscription</a>${business?'<a href="team.html">Team management</a>':''}<a href="plans.html">Subscription plans</a><button data-action="activate">Activate license</button><hr><button data-action="logout">Sign out</button></div></div></div></header><div class="subscription-expiry ${expiryInfo().expired?'expired':''}">${expiryText()}</div>`}
function mountShell(){document.querySelectorAll('[data-nusoq-shell]').forEach(el=>el.innerHTML=shellHtml());bindShell()}
function bindShell(){const u=document.querySelector('#nusoqUserBtn'),m=document.querySelector('#nusoqUserMenu');if(u&&m)u.onclick=e=>{e.stopPropagation();m.classList.toggle('on')};document.addEventListener('click',e=>{if(m&&!e.target.closest('.user-wrap'))m.classList.remove('on')});document.querySelectorAll('[data-action="activate"]').forEach(b=>b.onclick=()=>showActivation());document.querySelectorAll('[data-action="logout"]').forEach(b=>b.onclick=()=>alert('Sign out will connect to Supabase Auth in the production version.'))}
function syncShell(){mountShell();syncToolCards();syncModeBlocks()}
let pendingTool='';
function purchaseUrl(tool){const a=account();return (a.purchaseUrls&&a.purchaseUrls[tool])||a.sallaUrl||`plans.html?tool=${encodeURIComponent(tool)}`}
function ensureLockedToolModal(){if(document.querySelector('#lockedToolModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="modal-bg" id="lockedToolModal"><div class="modal locked-tool-modal"><div class="modal-head"><div><span class="badge plan">LOCKED TOOL</span><h3 id="lockedToolName" style="margin-top:9px">Tool access required</h3><p id="lockedToolDesc">Activate an existing license or purchase access to continue.</p></div><button class="close" data-close>×</button></div><div class="modal-body"><div class="locked-choice-grid"><button class="locked-choice" id="lockedActivate"><span class="locked-choice-ico">⌁</span><strong>Activate license</strong><small>Already purchased? Enter your serial number and unlock this tool.</small></button><a class="locked-choice" id="lockedPurchase" href="plans.html"><span class="locked-choice-ico">↗</span><strong>Purchase / Subscribe</strong><small>Open the purchase page for this tool.</small></a></div></div></div></div>`);document.querySelectorAll('#lockedToolModal [data-close]').forEach(b=>b.onclick=()=>document.querySelector('#lockedToolModal').classList.remove('on'));document.querySelector('#lockedActivate').onclick=()=>{document.querySelector('#lockedToolModal').classList.remove('on');showActivation(pendingTool)};}
function showLockedTool(tool){pendingTool=tool;ensureLockedToolModal();const meta=TOOLS[tool]||{name:'This tool'};document.querySelector('#lockedToolName').textContent=meta.name;document.querySelector('#lockedToolDesc').textContent=`${meta.name} is not included in your current ${mode()==='business'?'Business':'Personal'} access.`;document.querySelector('#lockedPurchase').href=purchaseUrl(tool);document.querySelector('#lockedToolModal').classList.add('on')}
function syncToolCards(){document.querySelectorAll('[data-tool]').forEach(card=>{const t=card.dataset.tool,s=status(t);card.dataset.state=s;card.classList.toggle('active',s==='active');const badge=card.querySelector('.badge');if(badge){badge.className='badge '+s;badge.textContent=s==='active'?'ACTIVE':s==='plan'?'LOCKED':'COMING SOON'}const action=card.querySelector('[data-tool-action]');if(action){action.textContent=s==='active'?'Open tool →':s==='plan'?'Activate or purchase':'Coming soon';action.disabled=s==='soon';action.onclick=e=>{e.preventDefault();e.stopPropagation();if(s==='active'&&TOOLS[t])location.href=TOOLS[t].href;else if(s==='plan')showLockedTool(t)}}if(s==='active'&&TOOLS[t]){card.style.cursor='pointer';card.onclick=e=>{if(e.target.closest('button,a'))return;location.href=TOOLS[t].href}}else if(s==='plan'){card.style.cursor='pointer';card.onclick=e=>{if(e.target.closest('button,a'))return;showLockedTool(t)}}else{card.style.cursor='default';card.onclick=null}})}
function syncModeBlocks(){document.querySelectorAll('[data-only-mode]').forEach(el=>el.classList.toggle('hidden',el.dataset.onlyMode!==mode()));document.querySelectorAll('[data-workspace-name]').forEach(el=>{const a=account();el.textContent=a.mode==='business'?(a.business.company||'Business Workspace'):'Personal Workspace'});document.querySelectorAll('[data-seat-count]').forEach(el=>{const s=seatInfo();el.textContent=`${s.used} users • ${s.capacity} included${s.extra?` • ${s.extra} extra`:''}`});document.querySelectorAll('[data-expiry]').forEach(el=>el.textContent=expiryText())}
function ensureActivationModal(){if(document.querySelector('#activationModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="modal-bg" id="activationModal"><div class="modal"><div class="modal-head"><div><h3>Activate license</h3><p id="activationPurpose">Enter the serial for your current workspace.</p></div><button class="close" data-close>×</button></div><div class="modal-body"><div class="activation-context"><span>Workspace</span><b id="activationMode"></b><span id="activationToolLabel"></span></div><label class="field" style="margin-top:12px">Serial number<input id="activationSerial" placeholder="NSQ-P-XXXX-XXXX"></label><div id="activationMsg" style="font-size:9px;margin-top:9px"></div></div><div class="modal-foot"><button class="btn sec" data-close>Cancel</button><button class="btn pri" id="activateSerialBtn">Activate</button></div></div></div>`);document.querySelectorAll('#activationModal [data-close]').forEach(b=>b.onclick=()=>document.querySelector('#activationModal').classList.remove('on'));document.querySelector('#activateSerialBtn').onclick=activateSerial}
function showActivation(tool=''){pendingTool=tool||'';ensureActivationModal();const a=account(),business=a.mode==='business';document.querySelector('#activationMode').textContent=business?'Business':'Personal';document.querySelector('#activationSerial').placeholder=business?'NSQ-B-XXXX-XXXX':'NSQ-P-XXXX-XXXX';document.querySelector('#activationSerial').value='';document.querySelector('#activationMsg').textContent='';document.querySelector('#activationPurpose').textContent=tool?`Activate access for ${TOOLS[tool]?.name||'this tool'}.`:'Enter the serial for your current workspace.';document.querySelector('#activationToolLabel').textContent=tool?`Tool: ${TOOLS[tool]?.name||tool}`:'';document.querySelector('#activationModal').classList.add('on')}
function activateSerial(){const a=account(),val=document.querySelector('#activationSerial').value.trim().toUpperCase(),msg=document.querySelector('#activationMsg');const required=a.mode==='business'?'NSQ-B-':'NSQ-P-';if(!val.startsWith(required)){msg.style.color='#b42318';msg.textContent='This serial belongs to a different workspace type.';return}const w=a[a.mode];w.active=true;w.license=val;if(pendingTool&&TOOLS[pendingTool]&&pendingTool!=='cad'&&!w.tools.includes(pendingTool))w.tools.push(pendingTool);save(a);msg.style.color='#0c6b58';msg.textContent=pendingTool?`${TOOLS[pendingTool].name} activated successfully.`:'License activated successfully.';setTimeout(()=>{document.querySelector('#activationModal').classList.remove('on');pendingTool='';syncShell()},650)}
function requireTool(tool){if(hasTool(tool))return true;showLockedTool(tool);return false}
function enhanceLegacyBoq(){if(!/boq\.html$/i.test(location.pathname))return;const apply=()=>{document.querySelectorAll('[data-copy]').forEach(x=>x.remove());const side=document.querySelector('.side');if(side&&!document.querySelector('#nusoqLegacyHome')){const a=document.createElement('a');a.id='nusoqLegacyHome';a.href='workspace.html';a.textContent='← Home / All Tools';a.style.cssText='display:block;margin:0 8px 10px;padding:9px 10px;border:1px solid #34404a;border-radius:9px;color:#cbd5df;text-decoration:none;font-size:10px;font-weight:800';side.insertBefore(a,side.children[1]||null)}const top=document.querySelector('.top .actions');if(top&&!document.querySelector('#nusoqLegacyAccount')){const b=document.createElement('a');b.id='nusoqLegacyAccount';b.href='account.html';b.textContent='Account';b.style.cssText='border:1px solid #e4e7ec;border-radius:9px;padding:9px 11px;text-decoration:none;color:#475467;font-size:10px;font-weight:800';top.insertBefore(b,top.firstChild)}if(top&&!document.querySelector('#nusoqLegacyExpiry')){const e=document.createElement('span');e.id='nusoqLegacyExpiry';e.textContent=expiryText();e.style.cssText='font-size:9px;color:#98a2b3;margin-right:7px;white-space:nowrap';top.insertBefore(e,top.firstChild)}};new MutationObserver(apply).observe(document.documentElement,{subtree:true,childList:true});setTimeout(apply,300);setTimeout(apply,1200)}
window.Nusoq={account,save,setMode,mode,workspace,hasTool,status,team,saveTeam,seatInfo,expiryInfo,expiryText,INCLUDED_BUSINESS_SEATS,mountShell,syncShell,requireTool,TOOLS,showActivation,showLockedTool};
document.addEventListener('DOMContentLoaded',()=>{mountShell();syncToolCards();syncModeBlocks();enhanceLegacyBoq()});document.addEventListener('nusoq:mode',()=>{syncToolCards();syncModeBlocks()});document.addEventListener('nusoq:team',syncModeBlocks);
})();